apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oizi2hz4i-python-ci
  namespace: tssc-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    path: ./components/oizi2hz4i-python/overlays/ci
    repoURL: https://github.com/rhtap-rhdh-qe/oizi2hz4i-python-gitops.git
    targetRevision: main
  destination:
    namespace: tssc-app-ci
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: tssc-gitops
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
