apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: oizi2hz4i-python 
  janus-idp.io/tekton: oizi2hz4i-python
  backstage.io/kubernetes-id: oizi2hz4i-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: oizi2hz4i-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml